pello_ser_o_no_ser:
    resource: "@PelloSerONoSerBundle/Resources/config/routing.yml"
    prefix:   /

artean:
    resource: "@CuatrovientosArteanBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_assetic:
    resource: .
    type:     assetic

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
