app:
    resource: "@AppBundle/Controller/"
    type:     annotation

artean:
    resource: "@CuatrovientosArteanBundle/Resources/config/routing.yml"
    prefix:   /


_assetic:
    resource: .
    type:     assetic