# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Cuatrovientos\ArteanBundle\Entity\User: 
            algorithm: md5
            encode_as_base64: false
            iterations: 0
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]        
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        
        artean_db_provider:
            entity:
                class: CuatrovientosArteanBundle:User
                property: login
                # if you're using multiple entity managers
                # manager_name: customer
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:            
            anonymous: ~

            pattern:    ^/
            context: session_key
            form_login:
                provider: artean_db_provider
                login_path: /login
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                #target_path_parameter: /admin/chatgroup
            logout:
                path:   /logout
                target: /login
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    my_custom_provider: "/login/check-custom"
                    my_github:          "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    access_control:
        - { path: ^/artean/admin/offer, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/artean/admin/user/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/artean/admin, roles: ROLE_ADMIN }
#        - { path: ^/artean/user, roles: ROLE_USER }
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
