cuatrovientos_artean_homepage:
    path:     /artean
    defaults: { _controller: CuatrovientosArteanBundle:Default:index }
    
cuatrovientos_artean_samples:
    path:     /artean/samples
    defaults: { _controller: FrameworkBundle:Template:template, template: CuatrovientosArteanBundle:Default:samples.html.twig }
    
################# center ##################

cuatrovientos_artean_center:
    path:     /artean/admin/center
    defaults: { _controller: CuatrovientosArteanBundle:Center:index }
    
cuatrovientos_artean_center_new:
    path:     /artean/admin/center/new
    defaults: { _controller: CuatrovientosArteanBundle:Center:newCenter }

cuatrovientos_artean_center_new_save:
    path:     /artean/admin/center/new/save
    defaults: { _controller: CuatrovientosArteanBundle:Center:newCenterSave }

cuatrovientos_artean_center_detail:
    path:     /artean/admin/center/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDetail }


cuatrovientos_artean_center_update_save:
    path:     /artean/admin/center/update/save
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerUpdateSave }

cuatrovientos_artean_center_update:
    path:     /artean/admin/center/update/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerUpdate }
    requirements: 
            'id' : '\d+'
            
cuatrovientos_artean_center_delete:
    path:     /artean/admin/center/delete/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDelete }
    requirements: 
            'id' : '\d+'

cuatrovientos_artean_center_delete_save:
    path:     /artean/admin/center/delete/save/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDeleteSave }
    requirements: 
            'id' : '\d+'
