cuatrovientos_artean_homepage:
#    path:     /artean
#    defaults: { _controller: CuatrovientosArteanBundle:Default:index }
    path:   /artean
    defaults: { _controller: FrameworkBundle:Template:template, template:  CuatrovientosArteanBundle:Default:stars.html.twig }
        
cuatrovientos_artean_homepage_root:
    path:     /
    defaults: { _controller: CuatrovientosArteanBundle:Default:index }
    
cuatrovientos_artean_samples:
    path:     /artean/samples
    defaults: { _controller: FrameworkBundle:Template:template, template: CuatrovientosArteanBundle:Default:samples.html.twig }

    
################# center ##################

cuatrovientos_artean_center:
    path:     /artean/admin/center
    defaults: { _controller: CuatrovientosArteanBundle:Center:index }
    
cuatrovientos_artean_center_new:
    path:     /artean/admin/center/new
    defaults: { _controller: CuatrovientosArteanBundle:Center:newCenter }

cuatrovientos_artean_center_new_save:
    path:     /artean/admin/center/new/save
    defaults: { _controller: CuatrovientosArteanBundle:Center:newCenterSave }

cuatrovientos_artean_center_detail:
    path:     /artean/admin/center/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDetail }


cuatrovientos_artean_center_update_save:
    path:     /artean/admin/center/update/save
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerUpdateSave }

cuatrovientos_artean_center_update:
    path:     /artean/admin/center/update/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerUpdate }
    requirements: 
            'id' : '\d+'
            
cuatrovientos_artean_center_delete:
    path:     /artean/admin/center/delete/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDelete }
    requirements: 
            'id' : '\d+'

cuatrovientos_artean_center_delete_save:
    path:     /artean/admin/center/delete/save/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Center:centerDeleteSave }
    requirements: 
            'id' : '\d+'
            
            
################# news ##################

cuatrovientos_artean_news:
    path:     /artean/admin/news
    defaults: { _controller: CuatrovientosArteanBundle:News:index }

cuatrovientos_artean_headlines:
    path:     /artean/open/news/headlines
    defaults: { _controller: CuatrovientosArteanBundle:News:showHeadlines }

cuatrovientos_artean_news_new:
    path:     /artean/admin/news/new
    defaults: { _controller: CuatrovientosArteanBundle:News:newNews }

cuatrovientos_artean_news_new_save:
    path:     /artean/admin/news/new/save
    defaults: { _controller: CuatrovientosArteanBundle:News:newNewsSave }

cuatrovientos_artean_news_detail:
    path:     /artean/admin/news/{id}
    defaults: { _controller: CuatrovientosArteanBundle:News:newsDetail }


cuatrovientos_artean_news_update_save:
    path:     /artean/admin/news/update/save
    defaults: { _controller: CuatrovientosArteanBundle:News:newsUpdateSave }

cuatrovientos_artean_news_update:
    path:     /artean/admin/news/update/{id}
    defaults: { _controller: CuatrovientosArteanBundle:News:newsUpdate }
    requirements: 
            'id' : '\d+'
            
cuatrovientos_artean_news_delete:
    path:     /artean/admin/news/delete/{id}
    defaults: { _controller: CuatrovientosArteanBundle:News:newsDelete }
    requirements: 
            'id' : '\d+'

cuatrovientos_artean_news_delete_save:
    path:     /artean/admin/news/delete/save/{id}
    defaults: { _controller: CuatrovientosArteanBundle:News:newsDeleteSave }
    requirements: 
            'id' : '\d+'
            

################# offer ##################

cuatrovientos_artean_open_offer_new:
    path:     /artean/open/offer/new
    defaults: { _controller: CuatrovientosArteanBundle:Offer:newOfferOpen }
    
cuatrovientos_artean_open_offer_save:
    path:     /artean/open/offer/save
    defaults: { _controller: CuatrovientosArteanBundle:Offer:newOfferSaveOpen }
    
################# offerAd ##################

cuatrovientos_artean_open_offer_ad_new:
    path:     /artean/open/offerad/new
    defaults: { _controller: CuatrovientosArteanBundle:OfferAd:newOfferAdOpen }
    
cuatrovientos_artean_open_offer_ad_save:
    path:     /artean/open/offerad/save
    defaults: { _controller: CuatrovientosArteanBundle:OfferAd:newOfferAdSaveOpen }
    
### admin    
cuatrovientos_artean_offer:
    path:     /artean/admin/offer
    defaults: { _controller: CuatrovientosArteanBundle:Offer:index }
    
cuatrovientos_artean_offer_new:
    path:     /artean/admin/offer/new
    defaults: { _controller: CuatrovientosArteanBundle:Offer:newOffer }

cuatrovientos_artean_offer_new_save:
    path:     /artean/admin/offer/new/save
    defaults: { _controller: CuatrovientosArteanBundle:Offer:newOfferSave }

cuatrovientos_artean_offer_detail:
    path:     /artean/admin/offer/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerDetail }

cuatrovientos_artean_offer_update_save:
    path:     /artean/admin/offer/update/save
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerUpdateSave }

cuatrovientos_artean_offer_update:
    path:     /artean/admin/offer/update/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerUpdate }
    requirements: 
            'id' : '\d+'
            
cuatrovientos_artean_offer_delete:
    path:     /artean/admin/offer/delete/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerDelete }
    requirements: 
            'id' : '\d+'

cuatrovientos_artean_offer_delete_save:
    path:     /artean/admin/offer/delete/save/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerDeleteSave }
    requirements: 
            'id' : '\d+'
   
cuatrovientos_artean_offer_process:
    path:     /artean/admin/offer/process/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:offerDeleteSave }
    requirements: 
            'id' : '\d+'

cuatrovientos_artean_offer_publish:
    path:     /artean/admin/offer/publish/{id}
    defaults: { _controller: CuatrovientosArteanBundle:Offer:newOfferPublish }
    requirements: 
            'id' : '\d+'

            
 ##### applicant ########################################33
cuatrovientos_artean_applicant_signin:        
    path:     /artean/applicant/signin
    defaults: { _controller: CuatrovientosArteanBundle:Applicant:applicantSignIn }

cuatrovientos_artean_applicant_signin_save:        
    path:     /artean/applicant/signin/save
    defaults: { _controller: CuatrovientosArteanBundle:Applicant:applicantSignInSave }

cuatrovientos_artean_applicant_signup:        
    path:     /artean/applicant/signup
    defaults: { _controller: CuatrovientosArteanBundle:Applicant:applicantSignUp }

cuatrovientos_artean_applicant_signup_save:        
    path:     /artean/applicant/signup/save
    defaults: { _controller: CuatrovientosArteanBundle:Applicant:applicantSignUpSave }


#### user 
cuatrovientos_artean_login:
    path:     /login
    defaults: { _controller: CuatrovientosArteanBundle:Security:login }

cuatrovientos_artean_login_check:
    path:     /login_check
    defaults: { _controller: CuatrovientosArteanBundle:Security:loginCheck }

cuatrovientos_artean_logout:
    path:     /logout
    defaults: { _controller: CuatrovientosArteanBundle:Security:logout }

