services:
##    cuatrovientos_artean.passwordLength:    8
#    cuatrovientos_artean.example:
#        class: Cuatrovientos\ArteanBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

##    cuatrovientos_artean.passwordGenerator:
##        class: Cuatrovientos\ArteanBundle\PasswordGenerator
##        arguments:  ['%cuatrovientos_artean.passwordLength%']
    cuatrovientos_artean.utils.permalink:
        class: Cuatrovientos\ArteanBundle\Service\Utils\Permalink
    inventory.security.sha1_password_encoder:
        class: Cuatrovientos\ArteanBundle\Security\Encoder\Sha1PasswordEncoder

    cuatrovientos_artean.dao.company:
         class: Cuatrovientos\ArteanBundle\Service\DAO\CompanyDAO
         arguments: ['CuatrovientosArteanBundle:Company', '@doctrine.orm.entity_manager' ]

    cuatrovientos_artean.bo.company:
         class: Cuatrovientos\ArteanBundle\Service\Business\CompanyBusiness
         arguments: ['@cuatrovientos_artean.dao.company']

    cuatrovientos_artean.dao.workorder:
         class: Cuatrovientos\ArteanBundle\Service\DAO\WorkOrderDAO
         arguments: ['CuatrovientosArteanBundle:WorkOrder', '@doctrine.orm.entity_manager' ]

    cuatrovientos_artean.bo.workorder:
         class: Cuatrovientos\ArteanBundle\Service\Business\WorkOrderBusiness
         arguments: ['@cuatrovientos_artean.dao.workorder']