services:
##    cuatrovientos_artean.passwordLength:    8
#    cuatrovientos_artean.example:
#        class: Cuatrovientos\ArteanBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

##    cuatrovientos_artean.passwordGenerator:
##        class: Cuatrovientos\ArteanBundle\PasswordGenerator
##        arguments:  ['%cuatrovientos_artean.passwordLength%']
    cuatrovientos_artean.utils.permalink:
        class: Cuatrovientos\ArteanBundle\Service\Utils\Permalink
    inventory.security.sha1_password_encoder:
        class: Cuatrovientos\ArteanBundle\Security\Encoder\Sha1PasswordEncoder