Cuatrovientos\ArteanBundle\Entity\Center:
        name:
            - NotBlank: {message: 'title.validation.blank'}
            - Length: { 'min' : 3, 'minMessage' : 'title.validation.min'}            